server:
  port: 8081
  servlet:
    context-path: /tinyurl

spring:
  application:
    name: url
  data:
    mongodb:
      uri: mongodb://sysUser:xisto80@localhost:27017/
      database: tinyurl


app:
  expired: 5 #tempo em horas
  tamanho: 5 #tamanho da nova url
  char: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789