server:
  port: 8081
  servlet:
    context-path: /tu

spring:
  application:
    name: url
  mongodb:
    uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:27017/
    database: tinyurl


app:
  expired: 5 #tempo em horas
  size: 5 #tamanho da nova url
  char: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
  baseUrl: http://127.0.0.1:8081/tu/rd/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always